### ISSUE TITLE
cPlayerOptions is not defined

### ISSUE THREAD

**Issue by jozhn** [journey-ad/cPlayer-Typecho-Plugin#10]
Uncaught ReferenceError: cPlayerOptions is not defined
    at cp (79:147)
    at HTMLScriptElement.script.onload (79:176)

typecho 1.0

**Comment by journey-ad** [comment]
请提供一个出现此问题的页面地址

**Comment by jozhn** [comment]
https://dearjohn.cn/saying/75 改了typecho文件头不提示这个了，但也不显示播放器，麻烦看一下。用了instantclick~应该是这个原因

**Comment by jozhn** [comment]
[player id='http://music.163.com/#/song?id=185705'/]插入的音乐代码是这个，不过没有显示播放器也没有显示代码

**Comment by journey-ad** [comment]
@JohnStinky 只用输入id，对于这首歌是185705

**Comment by jozhn** [comment]
[player id='id=185705'/]这样依然不显示~~~

**Comment by journey-ad** [comment]
@JohnStinky 
`[player id="185705"/]`
说明文档的使用方法一节中有详细的说明

**Comment by noisky** [comment]
[player id='id=185705'/]
哥们你不感觉你多了一个id=吗
引号之内只填数字id就可以了
就像[player id='185705'/]

**Comment by jozhn** [comment]
。。。我打错了抱歉，哈哈哈，之前可以自动生成成那样的

**Comment by jozhn** [comment]
不过只有一首歌的时候我的歌曲列表只能显示半行是不是跟我的CSS有关？

**Comment by journey-ad** [comment]
@JohnStinky 你的`style.css`里对`.list`添加了15px的上下内边距，和播放列表的样式冲突了

**Comment by jozhn** [comment]
多谢~~
