### ISSUE TITLE
SSL下get url的问题，跟第六个问题类似

### ISSUE THREAD

**Issue by jozhn** [journey-ad/cPlayer-Typecho-Plugin#11]
[网址](https://dearjohn.cn/life/14)，Chrome会提示https://www.dearjohn.cn/action/cplayerapi?get=url&id=32785269 net::ERR_INSECURE_RESPONSE，就是说不安全，因为我www这个域名没有上SSL。

不过我typecho后台一直用的是@域名，为什么cPlayer会产生www域名呢，而且仅在这个页面上出现了，其他页面的音乐都正常，说明其他获取的都是@域名的链接啊。。另外我对www做了301跳转也是这样，麻烦看一下~谢谢

**Comment by journey-ad** [comment]
清空缓存看看

**Comment by jozhn** [comment]
清空缓存后暂时没有问题了~
