### ISSUE TITLE
想向前辈你请教一个问题

### ISSUE THREAD

**Issue by tihssiefiL** [journey-ad/cPlayer-Typecho-Plugin#14]
我最近在自学vue.js
然后想边学边做一个仿网易云的demo
大题骨架搭好之后才发现不知道怎么去获取网易云的资源，好在找到了你的api https://api.imjad.cn/cloudmusic.md
但目前在使用中我遇到一些问题难以解决希望得到你的帮助

我使用axios可以正确获取歌曲并且播放，但是在获取mv时，可以正确返回mv的url，但是video 播放时会显示403错误导致video标签无法播放视频，偶尔成功播放时却返回206只能播放一小段，我开始以为是跨域问题，但是我将mv的url直接在浏览器地址栏打开时却可以正常播放并拖动加载，这个问题困扰我好久依然找不到解决办法，希望你可以帮到我。

**Comment by journey-ad** [comment]
按照你的描述，出现403可能是因为网易服务器的防盗链策略，但我这里没有观察到有防盗链
说一下问题范围，是所有mv都这样还是一部分；你的网络环境；你的浏览器；使用的播放器等，最好有一个线上页面，方便判断问题原因
206状态码是正常的，用于分片下载，断点续传下载文件或播放音视频拖拉进度条都会出现206 [相关文档](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/206)

**Comment by tihssiefiL** [comment]
相同的URL在我的项目的video标签里就会出现上面的问题，但是单独在浏览器地址栏输入就可以播放。
第一种情况在调试工具里面看到referer是localhost:8080,而第二种的referer是126.music.com,我在想是否和这个有关系。
网是电信，浏览器Chrome，播放器尝试过video 和 vue 的vue-video-play(好像是基于video.js封装的）

不知道问什么npm run dev 正常编译的项目 在 build之后有的图片会webpack改编成其他名称导致最后找不到相关资源，webpack暂时还不知道怎么配置。

再次谢谢你
