### ISSUE TITLE
启用以后，页面展示不出来

### ISSUE THREAD

**Issue by OceanGZY** [journey-ad/cPlayer-Typecho-Plugin#17]
![image](https://user-images.githubusercontent.com/18324630/51994032-ec7be300-24ea-11e9-99f0-b400956723f0.png)

启用了插件， 也配置了内容，但是页面里却展示不出来， 请大佬指点一下
![image](https://user-images.githubusercontent.com/18324630/51994111-16350a00-24eb-11e9-840a-f6719251318c.png)

**Comment by journey-ad** [comment]
检查页面html内有无播放器相关代码，没有的话检查所用模板有无相应插件钩子

页脚钩子一般为`footer.php`内类似`<?php $this->footer(); ?>`的代码

**Comment by journey-ad** [comment]
从你的截图中留下的信息来看，你现在用的模板的header.php和footer.php中均没有插件钩子

下面是我所用模板的示例，你可以参考一下：

`header.php`中加入`
    <?php $this->header('generator=&template=&xmlrpc=&wlw=&commentReply=&rss1=&rss2=&atom='); ?>`

`footer.php`中加入`<?php $this->footer(); ?>`

**Comment by OceanGZY** [comment]
谢谢啦， 现在可以用了
