### ISSUE TITLE
启用后歌曲没加载出来，播放一段恐怖音频

### ISSUE THREAD

**Issue by CrazyBoyM** [journey-ad/cPlayer-Typecho-Plugin#18]
emmmmm
大晚上听恐怖音频
反复测试添加任何歌曲结果相同
求尽快解决

**Comment by journey-ad** [comment]
@CrazyBoyM 那段音频内容是“非常抱歉，本音乐可能由于以下原因，导致无法正常播放：服务器故障；音乐不具有版权。cPlayer”
这个问题是境外服务器版权问题，~~翻翻之前的issues，有提到解决方法~~ 记错了，是博客文章评论里提到过

#### 解决方法：
>在Action.php 57行之前加入一行`curl_setopt($curl, CURLOPT_HTTPHEADER, array('X-Real-IP: 1.1.0.0'));`试试看
>不行的话把1.1.0.0替换成任意一个中国大陆区域的ip地址再试试

**Comment by journey-ad** [comment]
若有补充问题请重开此 issue
