### ISSUE TITLE
有些歌曲ID放进来不能自动播放，歌词都会显示

### ISSUE THREAD

**Issue by GokuSun** [journey-ad/cPlayer-Typecho-Plugin#19]
发现有些歌曲ID放进来不能自动播放，歌词都会显示，比如蒋大为的《敢问路在何方》ID=27552548 罗佳音的《only you》id=25707134

**Comment by GokuSun** [comment]
经过多次测试，id位数少于8位的都能播放，等于8位的就不能自动播放，且F12浏览器后在console里发现：Failed to load resource :net :: ERR_CONNECTION_REFUSED

**Comment by GokuSun** [comment]
又发现一个8位能播放的ID:27552755,奈何不懂技术，只能手工测试，真让人头大

**Comment by journey-ad** [comment]
这个报错一般是网易那边服务器的问题，至于为何是8位报错这种规律，实在是不好猜，也没有很好的应对办法
你可以用这个插件试试能不能自动播放 [MoePlayer/APlayer-Typecho](https://github.com/MoePlayer/APlayer-Typecho)
如果能的话，保留这个issue，我有空的时候会看看怎么回事

**Comment by GokuSun** [comment]
昨晚又发现两个问题：
1、用外网网址（如f3322）编辑的博客，音乐自动播放正常，回家用内网地址（192.168.1.*）打开的时候音乐不能播放（手动点击播放也不行），猜测音乐链接地址未做外链和内链转换。
2、谷歌浏览器不会自动播放，360浏览器极速模式可以自动播放

**Comment by GokuSun** [comment]
测试了APlayer-Typecho无法播放音乐，他在说明里是http的方式连接的，现在网易云音乐都是https，好像解析不了了，我换了很多首歌都是没有任何反应

**Comment by GokuSun** [comment]
外网访问后，内网在访问同一个博客网页，音乐就无法播放，清空缓存后就可以，浏览器F12查看，发现连接地址会保留上一次访问的，应该是跟您设置的的软件缓存机制有关系

**Comment by GokuSun** [comment]
有大佬提供的思路注释Action.php第九行就可以解决问题了，但是好像说安全性有点问题

**Comment by journey-ad** [comment]
问题说明：
使用不同域名访问时，通过`Typecho_Common::url()`方法获取到的 url 均为首次访问的值，猜测 Typecho 在此处使用了缓存
插件提供的简易 api 会验证来源信息(referrer)，与当前页面域名不符则返回 403 错误，注释掉`Action.php`中`self::filterReferer();`部分相当于禁用了此功能，但可能导致 api 服务被滥用

理论上更好的解决方法是使用`$_SERVER['SERVER_NAME']`等拼接 api 的 url
