### ISSUE TITLE
插入网易云音乐仅能播放10秒

### ISSUE THREAD

**Issue by YatsukiRenka** [journey-ad/cPlayer-Typecho-Plugin#21]
rt，在个人网站里面插入了音乐，但是只能播放十秒……

https://kotoka.tech/about.html

**Comment by journey-ad** [comment]
网易云限制了海外主机的直接访问，解决办法可以参考https://github.com/journey-ad/cPlayer-Typecho-Plugin/issues/18

**Comment by YatsukiRenka** [comment]
谢谢大佬
