### ISSUE TITLE
播放器整体很好，不过目前来说发现几处BUG

### ISSUE THREAD

**Issue by noisky** [journey-ad/cPlayer-Typecho-Plugin#3]
1.IOS系统下 会无限显示 loading PC和安卓正常
如图 https://img.imjad.cn/images/2016/11/14/99F08D475C4AA000A0E17E9FD9263B461.png
2.打开网页会自动缓存音乐 手机打开也是（瞬间几兆流量就没了） 如果能改成点击播放后再开始缓存就完美了
测试地址：https://demo.noisky.cn/Music/player_test.html

**Comment by Copay** [comment]
嗯。。。。。。要不要尝试一下新版本？

**Comment by Copay** [comment]
如果没记错的话，旧版本如果检测到没有“响应完毕的事件方法”就不会加上loading来着。不知道jad用的是哪个版本。

**Comment by Copay** [comment]
嗯...

**Comment by journey-ad** [comment]
已修复 [dd4fe7e](https://github.com/journey-ad/cPlayer-Typecho-Plugin/commit/dd4fe7e8c255ebe627d18f6777938c2525467c4c)
