### ISSUE TITLE
编辑器没有插入音乐按钮是怎么回事？小白完全不明白啊{{|└(>o< )┘|}}

### ISSUE THREAD

**Issue by jacksparrowFF2** [journey-ad/cPlayer-Typecho-Plugin#4]
编辑器没有插入音乐按钮是怎么回事？(´･_･`)以及curl该怎么开启?(´･_･`)

**Comment by journey-ad** [comment]
插入按钮目前支持默认编辑器和Editor.md，其他编辑器可以使用快捷键```CTRL+M```开启插入面板，curl在安装php时默认开启，部分虚拟主机可能不支持，这个无法解决

**Comment by jacksparrowFF2** [comment]
好的，明白了，谢谢！

**Comment by jacksparrowFF2** [comment]
是不是可以理解为如果虚拟主机如果不支持curl的话，插入按钮就没法显示啊？

**Comment by jacksparrowFF2** [comment]
如果直接输入代码的话表示没问题（上面那个问题看起来好二），可我就是默认编辑器不显示啊？
![image](https://cloud.githubusercontent.com/assets/23632933/22614770/302eb5ec-eac2-11e6-8bbe-9c3b36f7cdeb.png)
