### ISSUE TITLE
启用了Https之后似乎无法正常使用？

### ISSUE THREAD

**Issue by StupidPz** [journey-ad/cPlayer-Typecho-Plugin#6]
点击播放按钮音乐无法正常播放？ie和360极速浏览器都尝试了一边

**Comment by noisky** [comment]
应该没问题的
可以参考 https://ffis.me/Music/player_test.html

**Comment by StupidPz** [comment]
代码放的网易云id 点击之后按钮会变 但是音乐不会自动播放，封面和歌词显示正常，test页面第一个我也无法正常播放，但是第二个可以正常播放

**Comment by journey-ad** [comment]
长久未提供更多信息，若需要请再次开启
