### ISSUE TITLE
使用EditorMD编辑器 如何添加音乐？

### ISSUE THREAD

**Issue by yanaex** [journey-ad/cPlayer-Typecho-Plugin#7]
没有按钮。

**Comment by noisky** [comment]
直接按照使用说明中的格式添加即可

**Comment by yanaex** [comment]
页面是空白状态

**Comment by yanaex** [comment]
是主题的问题 换回默认主题可以显示..但播放按钮无法点击 使用的是Chrome 59，使用Edge浏览器可以让播放按钮变为播放中状态，进度条一直不动。插件目录给的755权限。主机是CentOS6.5 oneinstack的lnmp，还需要装什么额外环境吗?

**Comment by yanaex** [comment]
已编译安装curl扩展 还是无法解决

**Comment by journey-ad** [comment]
请提供一个测试页面以便排查问题

**Comment by yanaex** [comment]
https://nishuo.me/start-page.html

**Comment by journey-ad** [comment]
检查你所用主题的`header.php`中有无类似`<?php $this->header(); ?>`的代码，如果没有，加在合适位置后重试。

**Comment by nishuo** [comment]
添加到了header.php第二行<?php $this->header(); ?>
前台页面无法显示播放器。

**Comment by yanaex** [comment]
显示出来 播放按钮无法点击 
Chrome 59
无法正常使用

**Comment by journey-ad** [comment]
现在用的是旧api，有一部分歌曲不能解析，下次更新会更换为新版api，暂时先换一首或使用本地音乐吧

**Comment by yanaex** [comment]
F12有报错。
cplayer.min.js?v=1.2.5:1 
cPlayerv2.4.5


cplayer.min.js?v=1.2.5:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Comment by journey-ad** [comment]
这个是播放器的问题，据作者的说法是不用管它，我对 JavaScript 不是很熟悉，所以无法提供帮助
可以向 @Copay 询问具体情况

**Comment by Copay** [comment]
那个报错不用管来着...我看看别的播放器怎么解决...

**Comment by Copay** [comment]
修正完毕,原因是混淆了一个事件和一个方法...

**Comment by yanaex** [comment]
github还没有更新。

**Comment by Copay** [comment]
jad可能休息了，等明天看看吧，或者到copay/cplayer手动替换掉

**Comment by yanaex** [comment]
Thanks

**Comment by yanaex** [comment]
Chrome 59 播放器按钮无法点击
Firefox 点击按钮变为播放状态 进度条不加载 无声音。
地址是https://nishuo.me/45.html
cache目录为777权限

**Comment by Copay** [comment]
https://nishuo.me/action/cplayerapi?get=url&id=482056804

**Comment by Copay** [comment]
URL有问题,无法加载.

**Comment by yanaex** [comment]
403 什么问题？

**Comment by Copay** [comment]
哪儿有403

**Comment by journey-ad** [comment]
将```Action.php```第23行获取到的```$cexecute```的值用```var_dump()```打印出来看看

**Comment by journey-ad** [comment]
bug已重现，等待修复

**Comment by yanaex** [comment]
git pull 后 重新启用插件 按钮可以点击   说的是。。灰常抱歉.. 一个机器人的声音
换了几个歌都是这样 滑稽

**Comment by journey-ad** [comment]
境外服务器的问题，稍后尝试修复一下

**Comment by journey-ad** [comment]
在```Action.php```第62行之前加入```curl_setopt($curl, CURLOPT_HTTPHEADER, array('X-Real-IP: 1.1.0.0'));```试试看
不行的话把```1.1.0.0```替换成任意一个中国大陆区域的ip地址再试试

**Comment by yanaex** [comment]
将`curl_setopt($curl, CURLOPT_HTTPHEADER, array('X-Real-IP: 119.29.29.29'));` 加入62行前。
已解决。谢谢。
